<a href="https://colab.research.google.com/github/bolafadipe/Aicore-practicals/blob/main/module_4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

### Challenge 1.

Fancy indexing
- Look at the numpy docs to explore all the ways which you can use numpy to generate tensors/matrices/arrays of random numbers

- Create a matrix of random numbers with 4 rows and 6 columns

- Index the element on the 3rd row, 2nd col

- Index all of the even rows

- Index all of the elements on even rows and odd columns

- Index the elements along the diagonal

In [1]:
import numpy as np

In [4]:
# matrix of random integers with 4 rows and 6 columns
array = np.random.randint(10, size=(4, 6))
print(array)

[[7 3 7 2 8 9]
 [5 5 0 4 4 1]
 [2 4 0 8 2 9]
 [8 7 2 6 8 8]]


In [7]:
# indexing the element on the 3rd row and 2nd col
array[2,1]

4

In [11]:
# indexing all even rows
array[1::2]

array([[5, 5, 0, 4, 4, 1],
       [8, 7, 2, 6, 8, 8]])

In [14]:
# indexing all elements in even rows and odd columns
array[1::2, ::2]

array([[5, 0, 4],
       [8, 2, 8]])

### Challenge 2:
Broadcasting
- Create a random matrix of binary values

- Create a vector with as many rows as the matrix containing random positive integers between 1 and 5

- Add the vector to every column using broadcasting

- Create a new matrix by multiplying the columns of the original by the vector

- Create a new matrix by multiplying every element by a scalar value

In [16]:
# create random matrix of binary values
rand_matrix = np.random.randint(2, size=(4,6))

In [17]:
rand_matrix

array([[1, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 1, 1],
       [1, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1, 0]])

In [18]:
# create random vector with as many rows as rand_matrix
rand_vector = np.random.randint(1,5, size=(4,6))

In [19]:
rand_vector

array([[1, 3, 4, 2, 1, 3],
       [3, 1, 2, 2, 4, 2],
       [1, 4, 1, 4, 4, 3],
       [1, 4, 2, 3, 2, 4]])

In [20]:
new_vec = rand_matrix + rand_vector

In [21]:
new_vec

array([[2, 3, 4, 3, 2, 3],
       [4, 2, 2, 2, 5, 3],
       [2, 4, 2, 5, 4, 4],
       [1, 4, 2, 3, 3, 4]])

In [22]:
new_mat = rand_matrix * rand_vector

In [23]:
new_mat

array([[1, 0, 0, 2, 1, 0],
       [3, 1, 0, 0, 4, 2],
       [1, 0, 1, 4, 0, 3],
       [0, 0, 0, 0, 2, 0]])

In [24]:
# multiply by a scalar
b = 2
print(b*rand_vector)

[[2 6 8 4 2 6]
 [6 2 4 4 8 4]
 [2 8 2 8 8 6]
 [2 8 4 6 4 8]]
